CREATE TABLE color
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color_code  VARCHAR(255),
    color_label VARCHAR(255),
    color_hex   VARCHAR(255),
    CONSTRAINT pk_color PRIMARY KEY (id)
);

CREATE TABLE image
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE lifecycle
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lifecycle_status VARCHAR(255),
    CONSTRAINT pk_lifecycle PRIMARY KEY (id)
);

CREATE TABLE widget
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    blurb        VARCHAR(255),
    rating       INTEGER,
    quantity     INTEGER,
    price        DOUBLE PRECISION,
    slug         VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    color_id     INTEGER,
    image_id     INTEGER,
    lifecycle_id INTEGER,
    CONSTRAINT pk_widget PRIMARY KEY (id)
);

ALTER TABLE widget
    ADD CONSTRAINT FK_WIDGET_ON_COLOR FOREIGN KEY (color_id) REFERENCES color (id);

ALTER TABLE widget
    ADD CONSTRAINT FK_WIDGET_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE widget
    ADD CONSTRAINT FK_WIDGET_ON_LIFECYCLE FOREIGN KEY (lifecycle_id) REFERENCES lifecycle (id);